#! /bin/bash

echo

# remove virtual environment
# (https://github.com/orgs/python-poetry/discussions/3690#discussioncomment-5293709)
"./script/_poetry" env remove python3
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
   echo
   exit $EXIT_CODE
fi

echo
